I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 404, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 423, in <module>
    renpy.save("_reload-1", "reload save game")
Exception: Not saved - no valid save locations.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 404, in script
    python hide:
  File "C:\Users\Andrew\Downloads\renpy-6.99.13-sdk\renpy-6.99.13-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Andrew\Downloads\renpy-6.99.13-sdk\renpy-6.99.13-sdk\renpy\python.py", line 1764, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00keymap.rpy", line 423, in <module>
    renpy.save("_reload-1", "reload save game")
  File "C:\Users\Andrew\Downloads\renpy-6.99.13-sdk\renpy-6.99.13-sdk\renpy\loadsave.py", line 315, in save
    location.save(slotname, sr)
  File "C:\Users\Andrew\Downloads\renpy-6.99.13-sdk\renpy-6.99.13-sdk\renpy\savelocation.py", line 407, in save
    raise Exception("Not saved - no valid save locations.")
Exception: Not saved - no valid save locations.

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
CS Bounciness Vol. 2 1.0RC1
